#include "../../../version.h"
#if !defined(BACKPROP_TOOLS_NN_LAYERS_DENSE_OPERATIONS_CPU_H) && (BACKPROP_TOOLS_USE_THIS_VERSION == 1)
#define BACKPROP_TOOLS_NN_LAYERS_DENSE_OPERATIONS_CPU_H

#include "operations_generic.h"

BACKPROP_TOOLS_NAMESPACE_WRAPPER_START
namespace backprop_tools{
}
BACKPROP_TOOLS_NAMESPACE_WRAPPER_END

#endif
