add_executable(metra cli.cpp)
target_include_directories(metra PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_compile_features(metra PRIVATE cxx_std_17)
if(RL_TOOLS_COMMIT_HASH)
    target_compile_definitions(metra PRIVATE METRA_COMMIT=${RL_TOOLS_COMMIT_HASH})
endif()
if(RL_TOOLS_COMMIT_TIME)
    target_compile_definitions(metra PRIVATE METRA_COMMIT_TIME=${RL_TOOLS_COMMIT_TIME})
endif()
