[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hyperdrone"
version = "1.0.0"
authors = [{name = "Jonas Eschmann", email = "jonas.eschmann@gmail.com"}]
license = {text = "MIT"}
description = "The fastest drone simulator and renderer (raytracer)."
requires-python = ">=3.9"
dependencies = ["numpy", "nanobind>=2.0"]

[project.optional-dependencies]
examples = ["scipy", "matplotlib", "imageio", "imageio-ffmpeg"]
gym = ["gymnasium>=1.0"]

[tool.hatch.build.targets.wheel]
packages = ["hyperdrone"]

[tool.hatch.build.targets.sdist]
only-include = ["hyperdrone", "hatch_build.py", "README.md", "pyproject.toml"]

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"
