#include "version.h"
#if !defined(BACKPROP_TOOLS_BACKPROP_TOOLS_H) && (BACKPROP_TOOLS_USE_THIS_VERSION == 1)
#define BACKPROP_TOOLS_BACKPROP_TOOLS_H
//#define BACKPROP_TOOLS_NAMESPACE_WRAPPER test_ns
#ifndef BACKPROP_TOOLS_NAMESPACE_WRAPPER
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_START
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_END
#else
#define BACKPROP_TOOLS_NAMESPACE BACKPROP_TOOLS_NAMESPACE_WRAPPER ::backprop_tools
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_START namespace BACKPROP_TOOLS_NAMESPACE_WRAPPER {
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_END }
#endif
#endif

#define BACKPROP_TOOLS_TARGET_COMMIT_HASH fea9e60f01022880379374001e26f2a7678ab42e
#define BACKPROP_TOOLS_TARGET_COMMIT_HASH_SHORT 16689638
