#include "version.h"
#if (defined(BACKPROP_TOOLS_DISABLE_INCLUDE_GUARDS) || !defined(BACKPROP_TOOLS_BACKPROP_TOOLS_H)) && (BACKPROP_TOOLS_USE_THIS_VERSION == 1)
#pragma once
#define BACKPROP_TOOLS_BACKPROP_TOOLS_H
//#define BACKPROP_TOOLS_NAMESPACE_WRAPPER test_ns
#ifndef BACKPROP_TOOLS_NAMESPACE_WRAPPER
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_START
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_END
#else
#define BACKPROP_TOOLS_NAMESPACE BACKPROP_TOOLS_NAMESPACE_WRAPPER ::backprop_tools
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_START namespace BACKPROP_TOOLS_NAMESPACE_WRAPPER {
#define BACKPROP_TOOLS_NAMESPACE_WRAPPER_END }
#endif

BACKPROP_TOOLS_NAMESPACE_WRAPPER_START
namespace backprop_tools{
    template <auto T_C>
    struct Constant{
        static constexpr auto C = T_C;
    };
}
BACKPROP_TOOLS_NAMESPACE_WRAPPER_END


#endif

//#define BACKPROP_TOOLS_TARGET_COMMIT_HASH 111f0b82ba87ee4f1938f4d85ee2d266e70f4498
//#define BACKPROP_TOOLS_TARGET_COMMIT_HASH_SHORT 1122059
