if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()
if(POLICY CMP0012)
    cmake_policy(SET CMP0012 NEW)
endif()
if(NOT DEFINED GIT_EXECUTABLE)
    message(FATAL_ERROR "GIT_EXECUTABLE is required")
endif()
if(NOT DEFINED RL_TOOLS_ROOT)
    message(FATAL_ERROR "RL_TOOLS_ROOT is required")
endif()
if(NOT DEFINED RL_TOOLS_IS_REPO)
    set(RL_TOOLS_IS_REPO FALSE)
endif()
if(NOT DEFINED PARENT_IS_REPO)
    set(PARENT_IS_REPO FALSE)
endif()
if(NOT DEFINED PARENT_ROOT)
    set(PARENT_ROOT "")
endif()

function(git_capture VAR REPO_DIR)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" ${ARGN}
        WORKING_DIRECTORY "${REPO_DIR}"
        RESULT_VARIABLE GIT_CAPTURE_RESULT
        OUTPUT_VARIABLE GIT_CAPTURE_OUTPUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT GIT_CAPTURE_RESULT EQUAL 0)
        set(GIT_CAPTURE_OUTPUT "")
    endif()
    set(${VAR} "${GIT_CAPTURE_OUTPUT}" PARENT_SCOPE)
endfunction()

function(hex_encode_bytes INPUT OUT_BYTES OUT_SIZE)
    string(HEX "${INPUT}" HEX_STR)
    string(LENGTH "${HEX_STR}" HEX_LEN)
    math(EXPR BYTE_COUNT "${HEX_LEN} / 2")
    set(BYTES "")
    set(I 0)
    while(I LESS HEX_LEN)
        string(SUBSTRING "${HEX_STR}" ${I} 2 BYTE)
        math(EXPR BYTE_INDEX "${I} / 2")
        math(EXPR BYTE_MOD "${BYTE_INDEX} % 16")
        if(BYTE_MOD EQUAL 0)
            string(APPEND BYTES "\n        ")
        endif()
        string(APPEND BYTES "0x${BYTE},")
        math(EXPR I "${I} + 2")
    endwhile()
    set(${OUT_BYTES} "${BYTES}" PARENT_SCOPE)
    set(${OUT_SIZE} "${BYTE_COUNT}" PARENT_SCOPE)
endfunction()

function(append_string_var OUT_VAR NAME VALUE)
    hex_encode_bytes("${VALUE}" BYTES SIZE)
    set(CONTENT "${${OUT_VAR}}    namespace { const unsigned char ${NAME}_storage[] = {${BYTES}0x00}; }\n")
    set(CONTENT "${CONTENT}    extern const char* const ${NAME} = reinterpret_cast<const char*>(${NAME}_storage);\n")
    set(${OUT_VAR} "${CONTENT}" PARENT_SCOPE)
endfunction()

function(append_commit_message OUT_VAR VALUE)
    hex_encode_bytes("${VALUE}" BYTES SIZE)
    set(CONTENT "${${OUT_VAR}}    extern const unsigned char commit_message_bytes[] = {${BYTES}0x00};\n")
    set(CONTENT "${CONTENT}    extern const std::size_t commit_message_size = ${SIZE};\n")
    set(${OUT_VAR} "${CONTENT}" PARENT_SCOPE)
endfunction()

function(append_repo_snapshot OUT_VAR NAMESPACE_NAME IS_REPO REPO_ROOT AVAILABLE_FLAG)
    set(CONTENT "${${OUT_VAR}}namespace ${NAMESPACE_NAME} {\n")
    if(NOT AVAILABLE_FLAG STREQUAL "none")
        if(AVAILABLE_FLAG)
            set(CONTENT "${CONTENT}    extern const bool available = true;\n")
        else()
            set(CONTENT "${CONTENT}    extern const bool available = false;\n")
        endif()
    endif()

    if(IS_REPO)
        git_capture(COMMIT "${REPO_ROOT}" rev-parse HEAD)
        git_capture(COMMIT_MESSAGE "${REPO_ROOT}" log -1 --pretty=%B)
        git_capture(DIFF "${REPO_ROOT}" diff --no-ext-diff)
        git_capture(DIFF_COLOR "${REPO_ROOT}" diff --no-ext-diff --color=always)
        git_capture(WORD_DIFF "${REPO_ROOT}" diff --no-ext-diff --word-diff)
        git_capture(WORD_DIFF_COLOR "${REPO_ROOT}" diff --no-ext-diff --word-diff --color=always)
        git_capture(DIFF_STAGED "${REPO_ROOT}" diff --cached --no-ext-diff)
        git_capture(DIFF_STAGED_COLOR "${REPO_ROOT}" diff --cached --no-ext-diff --color=always)
        git_capture(WORD_DIFF_STAGED "${REPO_ROOT}" diff --cached --no-ext-diff --word-diff)
        git_capture(WORD_DIFF_STAGED_COLOR "${REPO_ROOT}" diff --cached --no-ext-diff --word-diff --color=always)
        set(PATH_VAR "${REPO_ROOT}")
        if(NOT COMMIT)
            set(COMMIT "unknown")
        endif()
    else()
        set(COMMIT "not_a_repository")
        set(COMMIT_MESSAGE "")
        set(DIFF "")
        set(DIFF_COLOR "")
        set(WORD_DIFF "")
        set(WORD_DIFF_COLOR "")
        set(DIFF_STAGED "")
        set(DIFF_STAGED_COLOR "")
        set(WORD_DIFF_STAGED "")
        set(WORD_DIFF_STAGED_COLOR "")
        set(PATH_VAR "")
    endif()

    append_string_var(CONTENT commit "${COMMIT}")
    append_commit_message(CONTENT "${COMMIT_MESSAGE}")
    append_string_var(CONTENT diff "${DIFF}")
    append_string_var(CONTENT diff_color "${DIFF_COLOR}")
    append_string_var(CONTENT word_diff "${WORD_DIFF}")
    append_string_var(CONTENT word_diff_color "${WORD_DIFF_COLOR}")
    append_string_var(CONTENT diff_staged "${DIFF_STAGED}")
    append_string_var(CONTENT diff_staged_color "${DIFF_STAGED_COLOR}")
    append_string_var(CONTENT word_diff_staged "${WORD_DIFF_STAGED}")
    append_string_var(CONTENT word_diff_staged_color "${WORD_DIFF_STAGED_COLOR}")
    append_string_var(CONTENT path "${PATH_VAR}")
    set(CONTENT "${CONTENT}} // namespace ${NAMESPACE_NAME}\n\n")

    set(${OUT_VAR} "${CONTENT}" PARENT_SCOPE)
endfunction()

set(CONTENT "#include <cstddef>\n")
set(CONTENT "${CONTENT}namespace rl_tools { namespace utils { namespace extrack { namespace git {\n")
append_repo_snapshot(CONTENT rl_tools ${RL_TOOLS_IS_REPO} "${RL_TOOLS_ROOT}" none)
append_repo_snapshot(CONTENT project ${PARENT_IS_REPO} "${PARENT_ROOT}" ${PARENT_IS_REPO})
set(CONTENT "${CONTENT}}}}}\n")

set(TMP_FILE "${OUTPUT_FILE}.tmp")
get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${TMP_FILE}" "${CONTENT}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${TMP_FILE}" "${OUTPUT_FILE}")
file(REMOVE "${TMP_FILE}")
