#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
    typedef uint64_t RLtoolsInferenceTimestamp;
    // The following structs are generated by copying them from ../../executor/executor.h, removing all templates and replacing all float types "T" with float;
    typedef struct{
        bool OK:1;
        float MAGNITUDE;
    } RltoolsInferenceExecutorJitterStatus;
    typedef struct{
        bool OK:1;
        float MAGNITUDE;
    } RltoolsInferenceExecutorBiasStatus;
    typedef enum{
        OBSERVATION,
        CONTROL
    } RltoolsInferenceExecutorStatusSource;
    typedef enum{
        INTERMEDIATE,
        NATIVE
    } RltoolsInferenceExecutorStepType;
    typedef struct{
        bool reset:1;
        bool time_diff:1;
        bool force_sync:1;
    } RltoolsInferenceExecutorControlReasons;
    typedef struct {
        bool OK:1;
        bool TIMESTAMP_INVALID:1;
        bool LAST_CONTROL_TIMESTAMP_GREATER_THAN_LAST_OBSERVATION_TIMESTAMP:1;
        RltoolsInferenceExecutorStatusSource source:1;
        RltoolsInferenceExecutorStepType step_type:1;
        RltoolsInferenceExecutorControlReasons control_reasons_intermediate;
        RltoolsInferenceExecutorControlReasons control_reasons_native;
        RltoolsInferenceExecutorJitterStatus timing_jitter;
        RltoolsInferenceExecutorBiasStatus timing_bias;
    } RLtoolsInferenceExecutorStatus;
    void rl_tools_inference_executor_status_message(RLtoolsInferenceExecutorStatus status, char* target, int target_size);
#ifdef __cplusplus
}
#endif

