
#ifdef __cplusplus
extern "C" {
#endif
    typedef uint64_t RLtoolsInferenceTimestamp;
    // The following structs are generated by copying them from ../../executor/executor.h, removing all templates and replacing all float types "T" with float;
    struct JitterStatus{
        bool OK:1;
        float MAGNITUDE;
    };
    struct BiasStatus{
        bool OK:1;
        float MAGNITUDE;
    };
    typedef struct {
        bool OK:1;
        bool TIMESTAMP_INVALID:1;
        bool LAST_CONTROL_TIMESTAMP_GREATER_THAN_LAST_OBSERVATION_TIMESTAMP:1;
        enum Source{
            OBSERVATION,
            CONTROL
        };
        Source source:1;
        enum StepType{
            INTERMEDIATE,
            NATIVE
        };
        StepType step_type:1;
        struct ControlReasons{
            bool reset:1;
            bool time_diff:1;
            bool force_sync:1;
        };
        ControlReasons control_reasons_intermediate;
        ControlReasons control_reasons_native;
        JitterStatus timing_jitter;
        BiasStatus timing_bias;
    } RLtoolsInferenceExecutorStatus;
    void rl_tools_inference_executor_status_message(RLtoolsInferenceExecutorStatus status, char* target, int target_size);
#ifdef __cplusplus
}
#endif

