ARG BASE_IMAGE
FROM --platform=${TARGETPLATFORM:-linux/amd64} ${BASE_IMAGE}
RUN apt-get update && apt-get install -y \
    git
RUN git clone https://github.com/rl-tools/rl-tools.git /rl_tools && echo bump_1
WORKDIR /
ENV RL_TOOLS_FEATURE_FLAGS=""
