add_executable(test_rendering_raytracing_generic backend.cpp)
target_link_libraries(test_rendering_raytracing_generic PRIVATE RLtools::Core GTest::gtest_main)
gtest_discover_tests(test_rendering_raytracing_generic)

add_executable(test_rendering_raytracing_generic_scene scene.cpp)
target_link_libraries(test_rendering_raytracing_generic_scene PRIVATE RLtools::RLtools assimp::assimp rendering_raytracing_stb GTest::gtest_main)
gtest_discover_tests(test_rendering_raytracing_generic_scene)
