project(nn_models_resnet_inference_cuda CUDA)
if(RL_TOOLS_BACKEND_ENABLE_CUDA AND RL_TOOLS_BACKEND_ENABLE_CUDNN AND RL_TOOLS_ENABLE_HDF5)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CXX_STANDARD  20)
    add_executable(nn_models_resnet_inference_cuda ../resnet_inference_cuda.cu)
    target_link_libraries(nn_models_resnet_inference_cuda PRIVATE rl_tools_full)
    target_include_directories(nn_models_resnet_inference_cuda PRIVATE ${stb_SOURCE_DIR})
    set(RESNET_MICRO_BATCH_SIZE "256" CACHE STRING "Micro-batch size for CUDA ResNet training")
    add_executable(nn_models_resnet_imagenet_training_cuda ../imagenet_training_cuda.cu)
    set_target_properties(nn_models_resnet_imagenet_training_cuda PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
    target_link_libraries(nn_models_resnet_imagenet_training_cuda PRIVATE rl_tools_full nvjpeg)
    target_compile_definitions(nn_models_resnet_imagenet_training_cuda PRIVATE MICRO_BATCH_SIZE=${RESNET_MICRO_BATCH_SIZE})
    target_compile_options(nn_models_resnet_imagenet_training_cuda PRIVATE -O3)
    target_link_directories(nn_models_resnet_imagenet_training_cuda PRIVATE ${CMAKE_BINARY_DIR}/lib-workaround)
    target_link_options(nn_models_resnet_imagenet_training_cuda PRIVATE "LINKER:--disable-new-dtags")
endif()
