project(nn_models_resnet_inference_cuda CUDA)
if(RL_TOOLS_BACKEND_ENABLE_CUDA AND RL_TOOLS_BACKEND_ENABLE_CUDNN AND RL_TOOLS_ENABLE_HDF5)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CXX_STANDARD  20)
    add_executable(nn_models_resnet_inference_cuda ../resnet_inference_cuda.cu)
    target_link_libraries(nn_models_resnet_inference_cuda PRIVATE rl_tools_full)
    target_include_directories(nn_models_resnet_inference_cuda PRIVATE ${stb_SOURCE_DIR})
    find_package(Arrow QUIET)
    find_package(Parquet QUIET)
    if(Arrow_FOUND AND Parquet_FOUND)
        add_executable(nn_models_resnet_imagenet_training_cuda ../imagenet_training_cuda.cu)
        target_link_libraries(nn_models_resnet_imagenet_training_cuda PRIVATE rl_tools_full Arrow::arrow_shared Parquet::parquet_shared)
        target_include_directories(nn_models_resnet_imagenet_training_cuda PRIVATE ${stb_SOURCE_DIR})
        target_compile_options(nn_models_resnet_imagenet_training_cuda PRIVATE -O3)
        target_link_directories(nn_models_resnet_imagenet_training_cuda PRIVATE ${CMAKE_BINARY_DIR}/lib-workaround)
        target_link_options(nn_models_resnet_imagenet_training_cuda PRIVATE "LINKER:--disable-new-dtags")
    endif()
endif()
