cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/metadata.cmake")
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../../.." ABSOLUTE)
if(NOT DEFINED BUNDLE_DIR)
    message(FATAL_ERROR "Pass -DBUNDLE_DIR=<candidate bundle directory>")
endif()
find_program(IDE_GIT git REQUIRED)
find_program(IDE_TAR tar REQUIRED)
ide_run(commit "${IDE_GIT}" -C "${repository}" rev-parse HEAD)
ide_run(epoch "${IDE_GIT}" -C "${repository}" show -s --format=%ct HEAD)
file(MAKE_DIRECTORY "${BUNDLE_DIR}/examples")
ide_run(ignored "${IDE_TAR}" --format=ustar --sort=name --dereference --hard-dereference --owner=0 --group=0 --numeric-owner "--mtime=@${epoch}"
    -C "${repository}/include" -cf "${BUNDLE_DIR}/rl_tools_include.tar" rl_tools)
file(READ "${repository}/static/ide/examples.json" examples)
file(COPY_FILE "${repository}/static/ide/examples.json" "${BUNDLE_DIR}/examples.json" ONLY_IF_DIFFERENT)
set(manifest "{}")
ide_json_field(manifest rl_tools_commit "${commit}")
string(JSON manifest SET "${manifest}" source_date_epoch ${epoch})
ide_hash(manifest rl_tools_include "${BUNDLE_DIR}/rl_tools_include.tar")
ide_hash(manifest examples "${BUNDLE_DIR}/examples.json")
string(JSON count LENGTH "${examples}" examples)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
    string(JSON name MEMBER "${examples}" examples ${index})
    string(JSON source GET "${examples}" examples "${name}" source)
    file(COPY_FILE "${repository}/${source}" "${BUNDLE_DIR}/examples/${name}.cpp" ONLY_IF_DIFFERENT)
    ide_hash(manifest "example_${name}" "${BUNDLE_DIR}/examples/${name}.cpp")
endforeach()
file(CONFIGURE OUTPUT "${BUNDLE_DIR}/manifest.json" CONTENT "${manifest}\n" @ONLY)
