# FetchContent download and update command for one git checkout with the smallest possible transfer: a single branch or
# tag at depth 1, no other branches, no tags (CMake's own GIT_SHALLOW clones every branch tip). Idempotent: an existing
# checkout is moved to the ref's current tip with one depth-1 fetch and left alone when it is there already; when the
# repository cannot be reached, an existing checkout is kept with a warning so a build works offline.
# Arguments: -DGIT= -DREPOSITORY= -DREF=<branch or tag> -DDIRECTORY=
foreach(required GIT REPOSITORY REF DIRECTORY)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "fetch_source.cmake: -D${required} is required")
    endif()
endforeach()

function(rl_tools_ide_git output)
    execute_process(COMMAND ${GIT} ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "git ${ARGN} failed:\n${stderr}")
    endif()
    set(${output} "${stdout}" PARENT_SCOPE)
endfunction()

if(EXISTS ${DIRECTORY}/.git)
    execute_process(COMMAND ${GIT} -C ${DIRECTORY} remote get-url origin RESULT_VARIABLE has_origin OUTPUT_QUIET ERROR_QUIET)
    if(has_origin EQUAL 0)
        rl_tools_ide_git(ignored -C ${DIRECTORY} remote set-url origin ${REPOSITORY})
    else()
        rl_tools_ide_git(ignored -C ${DIRECTORY} remote add origin ${REPOSITORY})
    endif()
    rl_tools_ide_git(head -C ${DIRECTORY} rev-parse HEAD)
    execute_process(COMMAND ${GIT} -C ${DIRECTORY} fetch --depth 1 --no-tags origin ${REF} RESULT_VARIABLE fetched OUTPUT_QUIET ERROR_VARIABLE stderr)
    if(NOT fetched EQUAL 0)
        message(WARNING "Could not fetch ${REF} from ${REPOSITORY}; keeping ${DIRECTORY} at ${head}\n${stderr}")
        return()
    endif()
    rl_tools_ide_git(wanted -C ${DIRECTORY} rev-parse FETCH_HEAD)
    if(head STREQUAL wanted)
        message(STATUS "${DIRECTORY} is at ${REF} (${head})")
        return()
    endif()
    message(STATUS "Moving ${DIRECTORY} from ${head} to ${REF} (${wanted})")
    rl_tools_ide_git(ignored -c advice.detachedHead=false -C ${DIRECTORY} checkout --force --detach FETCH_HEAD)
else()
    if(IS_DIRECTORY ${DIRECTORY})
        file(GLOB_RECURSE existing_files LIST_DIRECTORIES false ${DIRECTORY}/*)
        if(existing_files)
            message(FATAL_ERROR "${DIRECTORY} exists, is not a git checkout and is not empty; move it away first")
        endif()
        file(REMOVE_RECURSE ${DIRECTORY})
    endif()
    message(STATUS "Cloning ${REPOSITORY} at ${REF} (depth 1, single ref) into ${DIRECTORY}")
    rl_tools_ide_git(ignored init --quiet ${DIRECTORY})
    rl_tools_ide_git(ignored -C ${DIRECTORY} remote add origin ${REPOSITORY})
    rl_tools_ide_git(ignored -C ${DIRECTORY} fetch --depth 1 --no-tags origin ${REF})
    rl_tools_ide_git(ignored -c advice.detachedHead=false -C ${DIRECTORY} checkout --detach FETCH_HEAD)
endif()
rl_tools_ide_git(head -C ${DIRECTORY} rev-parse HEAD)
message(STATUS "${DIRECTORY} at ${head}")
