# FetchContent download command for one pinned git checkout with the smallest possible transfer: a single tag (or commit)
# at depth 1, no other branches, no other tags. CMake's own GIT_SHALLOW clones every branch tip. Idempotent: an existing
# checkout is left alone when it is already at the pin and moved with a depth-1 fetch otherwise.
# Arguments: -DGIT= -DREPOSITORY= -DTAG=<tag or 40-character commit> -DDIRECTORY=
foreach(required GIT REPOSITORY TAG DIRECTORY)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "fetch_source.cmake: -D${required} is required")
    endif()
endforeach()

function(rl_tools_ide_git output)
    execute_process(COMMAND ${GIT} ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "git ${ARGN} failed:\n${stderr}")
    endif()
    set(${output} "${stdout}" PARENT_SCOPE)
endfunction()

# CMake's regular expressions have no {n} quantifier, hence the length check
string(LENGTH "${TAG}" tag_length)
if(tag_length EQUAL 40 AND TAG MATCHES "^[0-9a-f]+$")
    set(pin_is_commit TRUE)
else()
    set(pin_is_commit FALSE)
endif()

if(EXISTS ${DIRECTORY}/.git)
    rl_tools_ide_git(head -C ${DIRECTORY} rev-parse HEAD)
    execute_process(COMMAND ${GIT} -C ${DIRECTORY} rev-parse --verify --quiet "${TAG}^{commit}" RESULT_VARIABLE known OUTPUT_VARIABLE wanted OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(known EQUAL 0 AND head STREQUAL wanted)
        message(STATUS "${DIRECTORY} is at ${TAG} (${head})")
        return()
    endif()
    message(STATUS "Moving ${DIRECTORY} to ${TAG} (depth 1)")
    if(pin_is_commit)
        rl_tools_ide_git(ignored -C ${DIRECTORY} fetch --depth 1 origin ${TAG})
    else()
        rl_tools_ide_git(ignored -C ${DIRECTORY} fetch --depth 1 origin tag ${TAG} --no-tags)
    endif()
    rl_tools_ide_git(ignored -c advice.detachedHead=false -C ${DIRECTORY} checkout --force --detach ${TAG})
else()
    if(IS_DIRECTORY ${DIRECTORY})
        file(GLOB_RECURSE existing_files LIST_DIRECTORIES false ${DIRECTORY}/*)
        if(existing_files)
            message(FATAL_ERROR "${DIRECTORY} exists, is not a git checkout and is not empty; move it away first")
        endif()
        file(REMOVE_RECURSE ${DIRECTORY})
    endif()
    message(STATUS "Cloning ${REPOSITORY} at ${TAG} (depth 1, single ref) into ${DIRECTORY}")
    if(pin_is_commit)
        rl_tools_ide_git(ignored init --quiet ${DIRECTORY})
        rl_tools_ide_git(ignored -C ${DIRECTORY} remote add origin ${REPOSITORY})
        rl_tools_ide_git(ignored -C ${DIRECTORY} fetch --depth 1 origin ${TAG})
        rl_tools_ide_git(ignored -c advice.detachedHead=false -C ${DIRECTORY} checkout --detach FETCH_HEAD)
    else()
        rl_tools_ide_git(ignored -c advice.detachedHead=false clone --depth 1 --branch ${TAG} --single-branch --no-tags --progress ${REPOSITORY} ${DIRECTORY})
    endif()
endif()
rl_tools_ide_git(head -C ${DIRECTORY} rev-parse HEAD)
message(STATUS "${DIRECTORY} at ${head}")
