function(ide_wasi_flags compile_output link_output resource_dir llvm_module)
    set(compile "-mcpu=${RL_TOOLS_IDE_WASI_CPU}")
    string(APPEND compile " \"-ffile-prefix-map=${CMAKE_BINARY_DIR}=/rl-tools-ide-build\"")
    string(APPEND compile " \"-ffile-prefix-map=${IDE_LLVM_SOURCE}=/rl-tools-ide-sources/llvm-project\"")
    string(APPEND compile " \"-ffile-prefix-map=${IDE_LIBC_SOURCE}=/rl-tools-ide-sources/wasi-libc\"")
    if(resource_dir)
        string(APPEND compile " \"-resource-dir=${resource_dir}\"")
    endif()
    set(link "${compile}")
    if(llvm_module)
        string(APPEND compile " -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_GETPID -D_WASI_EMULATED_SIGNAL")
        string(APPEND link " -lwasi-emulated-mman -lwasi-emulated-getpid -lwasi-emulated-signal -Wl,--strip-all -Wl,--max-memory=4294967296 -Wl,-z,stack-size=8388608,--stack-first")
        if(RL_TOOLS_IDE_LTO STREQUAL "thin")
            string(APPEND compile " -flto=thin")
            string(APPEND link " -flto=thin -Wl,--thinlto-jobs=${RL_TOOLS_IDE_JOBS}")
        elseif(RL_TOOLS_IDE_LTO STREQUAL "full")
            string(APPEND compile " -flto")
            string(APPEND link " -flto")
        endif()
    endif()
    set(${compile_output} "${compile}" PARENT_SCOPE)
    set(${link_output} "${link}" PARENT_SCOPE)
endfunction()
