include_guard(GLOBAL)

function(ide_run output)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${ARGN} failed:\n${stderr}")
    endif()
    set(${output} "${stdout}" PARENT_SCOPE)
endfunction()

function(ide_json_field object key value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    string(JSON updated SET "${${object}}" "${key}" "\"${value}\"")
    set(${object} "${updated}" PARENT_SCOPE)
endfunction()

function(ide_hash object key path)
    file(SHA256 "${path}" hash)
    file(SIZE "${path}" size)
    set(updated "${${object}}")
    ide_json_field(updated "${key}_sha256" "${hash}")
    string(JSON updated SET "${updated}" "${key}_bytes" ${size})
    set(${object} "${updated}" PARENT_SCOPE)
endfunction()
