include_guard(GLOBAL)

function(ide_run output)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${ARGN} failed:\n${stderr}")
    endif()
    set(${output} "${stdout}" PARENT_SCOPE)
endfunction()

function(ide_json_string output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(ide_json_field object key value)
    ide_json_string(encoded "${value}")
    string(JSON updated SET "${${object}}" "${key}" "${encoded}")
    set(${object} "${updated}" PARENT_SCOPE)
endfunction()

function(ide_json_array output)
    set(array "[]")
    set(index 0)
    foreach(argument IN LISTS ARGN)
        string(REPLACE "|" ";" argument "${argument}")
        ide_json_string(encoded "${argument}")
        string(JSON array SET "${array}" ${index} "${encoded}")
        math(EXPR index "${index} + 1")
    endforeach()
    set(${output} "${array}" PARENT_SCOPE)
endfunction()

function(ide_read_array output object)
    string(JSON count LENGTH "${object}" ${ARGN})
    set(values)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE ${last})
            string(JSON value GET "${object}" ${ARGN} ${index})
            string(REPLACE ";" "\\;" value "${value}")
            list(APPEND values "${value}")
        endforeach()
    endif()
    set(${output} "${values}" PARENT_SCOPE)
endfunction()

function(ide_hash object key path)
    file(SHA256 "${path}" hash)
    file(SIZE "${path}" size)
    set(updated "${${object}}")
    ide_json_field(updated "${key}_sha256" "${hash}")
    string(JSON updated SET "${updated}" "${key}_bytes" ${size})
    set(${object} "${updated}" PARENT_SCOPE)
endfunction()
