cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/metadata.cmake")
find_program(IDE_TAR tar REQUIRED)
file(READ "${CONFIG}" manifest)
string(JSON epoch GET "${manifest}" source_date_epoch)
file(MAKE_DIRECTORY "${PACKAGE_DIR}")
set(staging "${PACKAGE_DIR}/sysroot")
file(REMOVE_RECURSE "${staging}")
file(MAKE_DIRECTORY "${staging}")
file(COPY "${SYSROOT_DIR}/" DESTINATION "${staging}")
file(COPY "${RESOURCE_HEADERS}/" DESTINATION "${staging}/include")
file(GLOB top_level RELATIVE "${staging}" "${staging}/*")
list(SORT top_level)
ide_run(ignored "${IDE_TAR}" --format=ustar --sort=name --dereference --hard-dereference
    --owner=0 --group=0 --numeric-owner "--mtime=@${epoch}" -C "${staging}" -cf "${PACKAGE_DIR}/sysroot.tar" ${top_level})
file(REMOVE_RECURSE "${staging}")
file(COPY_FILE "${MODULE}" "${PACKAGE_DIR}/llvm.wasm" ONLY_IF_DIFFERENT)
ide_hash(manifest llvm_wasm "${PACKAGE_DIR}/llvm.wasm")
ide_hash(manifest sysroot_tar "${PACKAGE_DIR}/sysroot.tar")
ide_run(host_compiler "${HOST_LLVM_BIN}/clang" --version)
ide_run(host_linker "${HOST_LLVM_BIN}/wasm-ld" --version)
string(REGEX REPLACE "\n.*" "" host_compiler "${host_compiler}")
string(REGEX REPLACE "\n.*" "" host_linker "${host_linker}")
ide_json_field(manifest host_compiler "${host_compiler}")
ide_json_field(manifest host_linker "${host_linker}")
ide_json_field(manifest host_compiler_path "${HOST_LLVM_BIN}/clang")
include("${LLVM_SOURCE_DIR}/cmake/Modules/LLVMVersion.cmake")
string(JSON suffix GET "${manifest}" llvm_version_suffix)
ide_json_field(manifest llvm_version "${LLVM_VERSION_MAJOR}.${LLVM_VERSION_MINOR}.${LLVM_VERSION_PATCH}${suffix}")
file(CONFIGURE OUTPUT "${PACKAGE_DIR}/toolchain.json" CONTENT "${manifest}\n" @ONLY)
string(JSON module_hash GET "${manifest}" llvm_wasm_sha256)
string(JSON sysroot_hash GET "${manifest}" sysroot_tar_sha256)
file(CONFIGURE OUTPUT "${PACKAGE_DIR}/SHA256SUMS" CONTENT "${module_hash}  llvm.wasm\n${sysroot_hash}  sysroot.tar\n" @ONLY)
