# Keeps WORKTREE a detached git worktree of the pinned LLVM commit with the patch series from PATCH_DIR applied, in name
# order, exactly once. A marker file records which series is applied; a different series or a different pin resets the
# worktree to the pristine commit and applies again. Idempotent and cheap when nothing changed.
# Arguments: -DGIT= -DSOURCE=<pristine checkout> -DWORKTREE= -DTAG=<tag or commit> -DPATCH_DIR=
foreach(required GIT SOURCE WORKTREE TAG PATCH_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "prepare_wasi_source.cmake: -D${required} is required")
    endif()
endforeach()

function(rl_tools_ide_git output)
    execute_process(COMMAND ${GIT} ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "git ${ARGN} failed:\n${stderr}")
    endif()
    set(${output} "${stdout}" PARENT_SCOPE)
endfunction()

file(GLOB patches ${PATCH_DIR}/*.patch)
list(SORT patches)
if(NOT patches)
    message(FATAL_ERROR "No patches in ${PATCH_DIR}")
endif()
set(series "")
foreach(patch IN LISTS patches)
    file(SHA256 ${patch} patch_sha256)
    get_filename_component(patch_name ${patch} NAME)
    string(APPEND series "${patch_sha256}  ${patch_name}\n")
endforeach()

rl_tools_ide_git(commit -C ${SOURCE} rev-parse --verify --quiet "${TAG}^{commit}")
set(marker ${WORKTREE}/.rl-tools-ide-patches)
if(NOT EXISTS ${WORKTREE}/.git)
    # ExternalProject pre-creates its source directories (empty), which git worktree add refuses; anything with files stays
    if(IS_DIRECTORY ${WORKTREE})
        file(GLOB_RECURSE existing_files LIST_DIRECTORIES false ${WORKTREE}/*)
        if(existing_files)
            message(FATAL_ERROR "${WORKTREE} exists, is not a git worktree and is not empty; move it away first")
        endif()
        file(REMOVE_RECURSE ${WORKTREE})
    endif()
    rl_tools_ide_git(ignored -C ${SOURCE} worktree prune)
    message(STATUS "Creating worktree ${WORKTREE} at ${TAG} (${commit})")
    rl_tools_ide_git(ignored -c advice.detachedHead=false -C ${SOURCE} worktree add --detach ${WORKTREE} ${commit})
else()
    rl_tools_ide_git(head -C ${WORKTREE} rev-parse HEAD)
    if(EXISTS ${marker})
        file(READ ${marker} applied)
    else()
        set(applied "")
    endif()
    if(head STREQUAL commit AND applied STREQUAL "${commit}\n${series}")
        message(STATUS "Worktree ${WORKTREE} is at ${TAG} with the current patch series")
        return()
    endif()
    # A series that merely grew is applied incrementally, so the files the earlier patches touched keep their timestamps
    # and the builds on top of the worktree do not recompile everything
    string(FIND "${commit}\n${series}" "${applied}" applied_position)
    if(head STREQUAL commit AND NOT applied STREQUAL "" AND applied_position EQUAL 0)
        string(LENGTH "${applied}" applied_length)
        string(SUBSTRING "${commit}\n${series}" ${applied_length} -1 remaining)
        string(REGEX MATCHALL "[^\n]+" remaining_lines "${remaining}")
        set(patches)
        foreach(line IN LISTS remaining_lines)
            string(REGEX REPLACE "^[0-9a-f]+  " "" patch_name "${line}")
            list(APPEND patches ${PATCH_DIR}/${patch_name})
        endforeach()
        message(STATUS "Worktree ${WORKTREE} has a prefix of the current series; applying the rest")
    else()
        message(STATUS "Resetting worktree ${WORKTREE} to ${TAG} (${commit})")
        rl_tools_ide_git(ignored -c advice.detachedHead=false -C ${WORKTREE} checkout --force --detach ${commit})
        file(REMOVE ${marker})
    endif()
endif()

foreach(patch IN LISTS patches)
    get_filename_component(patch_name ${patch} NAME)
    execute_process(COMMAND ${GIT} -C ${WORKTREE} apply --check ${patch} RESULT_VARIABLE applies OUTPUT_QUIET ERROR_VARIABLE check_error)
    if(NOT applies EQUAL 0)
        message(FATAL_ERROR "${patch_name} does not apply to ${TAG}:\n${check_error}\n"
            "Rebase the series with tools/ide/toolchain/rebase_patches.sh ${TAG}")
    endif()
    message(STATUS "Applying ${patch_name}")
    rl_tools_ide_git(ignored -C ${WORKTREE} apply ${patch})
endforeach()
file(WRITE ${marker} "${commit}\n${series}")
