# Assembles the resource directory the host clang uses for wasm32 builds: its own headers next to the builtins from stage 2.
# Arguments: -DCLANG= -DBUILTINS=<lib/wasm32-unknown-wasip1 directory> -DRESOURCE_DIR=
foreach(required CLANG BUILTINS RESOURCE_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "resource_dir.cmake: -D${required} is required")
    endif()
endforeach()
execute_process(COMMAND ${CLANG} -print-resource-dir RESULT_VARIABLE result OUTPUT_VARIABLE host_resource_dir OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT result EQUAL 0 OR NOT IS_DIRECTORY ${host_resource_dir}/include)
    message(FATAL_ERROR "${CLANG} -print-resource-dir did not name a directory with headers (${host_resource_dir})")
endif()
if(NOT EXISTS ${BUILTINS}/libclang_rt.builtins.a)
    message(FATAL_ERROR "${BUILTINS}/libclang_rt.builtins.a is missing; the compiler-rt stage did not install it")
endif()
file(REMOVE_RECURSE ${RESOURCE_DIR})
file(COPY ${host_resource_dir}/include DESTINATION ${RESOURCE_DIR})
file(COPY ${BUILTINS} DESTINATION ${RESOURCE_DIR}/lib)
message(STATUS "Resource directory ${RESOURCE_DIR}: headers from ${host_resource_dir}, builtins from ${BUILTINS}")
