include("${CMAKE_CURRENT_LIST_DIR}/metadata.cmake")

function(ide_fetch_sources output lock_file)
    include(FetchContent)
    find_program(IDE_GIT git REQUIRED)
    option(RL_TOOLS_OFFLINE_BUILD "Use existing dependency checkouts without checking for updates" OFF)
    if(RL_TOOLS_OFFLINE_BUILD)
        set(FETCHCONTENT_FULLY_DISCONNECTED ON)
    endif()
    file(READ "${lock_file}" lock)
    set(names ${ARGN})
    if(NOT names)
        set(names llvm-project wasi-libc)
    endif()
    set(resolved "{}")
    foreach(name IN LISTS names)
        string(REPLACE "-" "_" content_name "${name}")
        string(JSON entry GET "${lock}" sources "${name}")
        string(JSON repository GET "${entry}" repository)
        string(JSON ref GET "${entry}" ref)
        set(command "${CMAKE_COMMAND}" "-DGIT=${IDE_GIT}" "-DREPOSITORY=${repository}" "-DREF=${ref}"
            "-DDIRECTORY=<SOURCE_DIR>" -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/fetch_source.cmake")
        FetchContent_Declare(${content_name}
            DOWNLOAD_COMMAND ${command}
            UPDATE_COMMAND ${command}
            SOURCE_SUBDIR rl-tools-not-a-subproject)
        FetchContent_MakeAvailable(${content_name})
        set(directory "${${content_name}_SOURCE_DIR}")
        ide_run(commit "${IDE_GIT}" -C "${directory}" rev-parse HEAD)
        ide_json_field(entry commit "${commit}")
        ide_json_field(entry directory "${directory}")
        string(JSON resolved SET "${resolved}" "${name}" "${entry}")
    endforeach()
    set(${output} "${resolved}" PARENT_SCOPE)
endfunction()

function(ide_check_sources revision_file)
    find_program(IDE_GIT git REQUIRED)
    file(READ "${revision_file}" sources)
    string(JSON count LENGTH "${sources}")
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
        string(JSON name MEMBER "${sources}" ${index})
        string(JSON directory GET "${sources}" "${name}" directory)
        string(JSON expected GET "${sources}" "${name}" commit)
        ide_run(head "${IDE_GIT}" -C "${directory}" rev-parse HEAD)
        if(NOT head STREQUAL expected)
            message(FATAL_ERROR "${directory} moved from ${expected} to ${head}. Reconfigure before building.")
        endif()
        ide_run(changes "${IDE_GIT}" -C "${directory}" status --porcelain --untracked-files=normal)
        if(NOT changes STREQUAL "")
            message(FATAL_ERROR "${directory} has local changes; source packages must be built from clean checkouts.")
        endif()
    endforeach()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    ide_check_sources("${REVISION_FILE}")
endif()
