# Cross toolchain for wasm32-wasip1 driven by a host clang and lld. The superbuild (tools/ide/toolchain) hands every input in
# as a cache entry; try_compile re-reads this file in a fresh project, so those entries are forwarded explicitly.
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    RL_TOOLS_IDE_HOST_LLVM_BIN RL_TOOLS_IDE_TARGET RL_TOOLS_IDE_WASI_SYSROOT)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")

set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_C_COMPILER "${RL_TOOLS_IDE_HOST_LLVM_BIN}/clang")
set(CMAKE_CXX_COMPILER "${RL_TOOLS_IDE_HOST_LLVM_BIN}/clang++")
set(CMAKE_ASM_COMPILER "${RL_TOOLS_IDE_HOST_LLVM_BIN}/clang")
set(CMAKE_AR "${RL_TOOLS_IDE_HOST_LLVM_BIN}/llvm-ar")
set(CMAKE_RANLIB "${RL_TOOLS_IDE_HOST_LLVM_BIN}/llvm-ranlib")
set(CMAKE_NM "${RL_TOOLS_IDE_HOST_LLVM_BIN}/llvm-nm")
set(CMAKE_C_COMPILER_TARGET ${RL_TOOLS_IDE_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${RL_TOOLS_IDE_TARGET})
set(CMAKE_ASM_COMPILER_TARGET ${RL_TOOLS_IDE_TARGET})
set(CMAKE_SYSROOT "${RL_TOOLS_IDE_WASI_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_LINKER_DEPFILE_SUPPORTED OFF)
set(CMAKE_CXX_LINKER_DEPFILE_SUPPORTED OFF)
