cmake_minimum_required(VERSION 3.24)
file(REMOVE "${STAMP}")
if(NOT NODE OR NOT EXISTS "${NODE}")
    message(FATAL_ERROR "Verification requires Node.js 22+. Reconfigure after provisioning Node, or build only the package/bundle targets.")
endif()
execute_process(COMMAND "${NODE}" --version OUTPUT_VARIABLE version RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT version MATCHES "^v([0-9]+)[.]")
    message(FATAL_ERROR "Could not determine the Node.js version.")
endif()
if(CMAKE_MATCH_1 LESS 22)
    message(FATAL_ERROR "Node.js 22+ is required; found ${version}.")
endif()
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${BUILD_DIR}" --output-on-failure --no-tests=error -L "^${LABEL}$" --timeout 300 -j1 RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Toolchain verification failed.")
endif()
file(WRITE "${STAMP}" "${LABEL}\n")
