cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/../../../tools/ide/toolchain/cmake/metadata.cmake")
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
file(READ "${repository}/tools/ide/dependencies.json" lock)
file(READ "${BUNDLE_DIR}/toolchain/toolchain.json" manifest)
string(JSON format GET "${manifest}" format)
if(NOT format EQUAL 1)
    message(FATAL_ERROR "Unsupported manifest format: ${format}")
endif()
foreach(pair "llvm-project|llvm" "wasi-libc|wasi_libc")
    string(REPLACE "|" ";" pair "${pair}")
    list(GET pair 0 source)
    list(GET pair 1 prefix)
    foreach(field repository ref upstream)
        string(JSON expected GET "${lock}" sources "${source}" "${field}")
        string(JSON actual GET "${manifest}" "${prefix}_${field}")
        if(NOT expected STREQUAL actual)
            message(FATAL_ERROR "${prefix}_${field}: expected ${expected}, found ${actual}")
        endif()
    endforeach()
    string(JSON commit GET "${manifest}" "${prefix}_commit")
    string(LENGTH "${commit}" length)
    if(NOT length EQUAL 40 OR NOT commit MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "${prefix}_commit must identify the exact source revision")
    endif()
endforeach()
foreach(field target cpu llvm_version_suffix)
    string(JSON expected GET "${lock}" "${field}")
    string(JSON actual GET "${manifest}" "${field}")
    if(NOT expected STREQUAL actual)
        message(FATAL_ERROR "${field}: expected ${expected}, found ${actual}")
    endif()
endforeach()
set(sums "")
set(actual "{}")
foreach(pair "llvm.wasm|llvm_wasm" "sysroot.tar|sysroot_tar")
    string(REPLACE "|" ";" pair "${pair}")
    list(GET pair 0 file)
    list(GET pair 1 key)
    ide_hash(actual "${key}" "${BUNDLE_DIR}/toolchain/${file}")
    foreach(suffix sha256 bytes)
        string(JSON expected_value GET "${manifest}" "${key}_${suffix}")
        string(JSON actual_value GET "${actual}" "${key}_${suffix}")
        if(NOT expected_value STREQUAL actual_value)
            message(FATAL_ERROR "${file}: ${suffix} mismatch")
        endif()
    endforeach()
    string(JSON hash GET "${actual}" "${key}_sha256")
    string(APPEND sums "${hash}  ${file}\n")
endforeach()
file(READ "${BUNDLE_DIR}/toolchain/SHA256SUMS" recorded_sums)
if(NOT sums STREQUAL recorded_sums)
    message(FATAL_ERROR "SHA256SUMS does not match the manifest and artifacts")
endif()
file(READ "${BUNDLE_DIR}/manifest.json" bundle)
file(READ "${BUNDLE_DIR}/examples.json" examples)
set(files "rl_tools_include.tar|rl_tools_include" "examples.json|examples")
string(JSON count LENGTH "${examples}" examples)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
    string(JSON name MEMBER "${examples}" examples ${index})
    list(APPEND files "examples/${name}.cpp|example_${name}")
endforeach()
foreach(pair IN LISTS files)
    string(REPLACE "|" ";" pair "${pair}")
    list(GET pair 0 file)
    list(GET pair 1 key)
    ide_hash(actual "${key}" "${BUNDLE_DIR}/${file}")
    foreach(suffix sha256 bytes)
        string(JSON expected_value GET "${bundle}" "${key}_${suffix}")
        string(JSON actual_value GET "${actual}" "${key}_${suffix}")
        if(NOT expected_value STREQUAL actual_value)
            message(FATAL_ERROR "${file}: ${suffix} mismatch")
        endif()
    endforeach()
endforeach()
message(STATUS "PASS: bundle hashes and toolchain provenance match ${BUNDLE_DIR}")
