cmake_minimum_required(VERSION 3.24)
set(missing "")
find_program(executable NAMES "${PROGRAM}")
if(NOT executable)
    list(APPEND missing "${PROGRAM}")
endif()
foreach(file IN LISTS FILES)
    if(NOT EXISTS "${file}")
        list(APPEND missing "${file}")
    endif()
endforeach()
if(missing)
    if(REQUIRED)
        message(FATAL_ERROR "Missing IDE prerequisites: ${missing}")
    endif()
    message("SKIP: IDE prerequisite missing: ${missing}")
    return()
endif()
execute_process(COMMAND "${executable}" ${ARGUMENTS} RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    if(result EQUAL 77 AND NOT REQUIRED)
        message("SKIP: IDE prerequisite unavailable")
    else()
        message(FATAL_ERROR "IDE test failed (${result})")
    endif()
endif()
