if(RL_TOOLS_ENABLE_TAR AND RL_TOOLS_TEST_DATA_PATH)
    add_executable(test_dyn dyn.cpp)
    target_link_libraries(test_dyn RLtools::RLtools GTest::gtest_main)
    target_compile_definitions(test_dyn PRIVATE RL_TOOLS_TEST_DATA_PATH=${RL_TOOLS_TEST_DATA_PATH})
    gtest_discover_tests(test_dyn)
endif()
if(RL_TOOLS_ENABLE_HDF5 AND RL_TOOLS_TEST_DATA_PATH)
    add_executable(test_dyn_hdf5 dyn_hdf5.cpp)
    target_link_libraries(test_dyn_hdf5 RLtools::RLtools GTest::gtest_main)
    target_compile_definitions(test_dyn_hdf5 PRIVATE RL_TOOLS_TEST_DATA_PATH=${RL_TOOLS_TEST_DATA_PATH})
    gtest_discover_tests(test_dyn_hdf5)
endif()
