if(RL_TOOLS_ENABLE_TAR AND RL_TOOLS_TEST_DATA_PATH)
    add_executable(test_dyn dyn.cpp)
    target_link_libraries(test_dyn RLtools::RLtools GTest::gtest_main)
    target_compile_definitions(test_dyn PRIVATE RL_TOOLS_TEST_DATA_PATH=${RL_TOOLS_TEST_DATA_PATH})
    gtest_discover_tests(test_dyn)
endif()
if(RL_TOOLS_ENABLE_HDF5 AND RL_TOOLS_TEST_DATA_PATH)
    add_executable(test_dyn_hdf5 dyn_hdf5.cpp)
    target_link_libraries(test_dyn_hdf5 RLtools::RLtools GTest::gtest_main)
    target_compile_definitions(test_dyn_hdf5 PRIVATE RL_TOOLS_TEST_DATA_PATH=${RL_TOOLS_TEST_DATA_PATH})
    gtest_discover_tests(test_dyn_hdf5)

    add_executable(test_dyn_wasm_generate dyn_wasm_generate.cpp)
    target_link_libraries(test_dyn_wasm_generate RLtools::RLtools)
    target_compile_definitions(test_dyn_wasm_generate PRIVATE RL_TOOLS_TEST_DATA_PATH=${RL_TOOLS_TEST_DATA_PATH})
    add_test(NAME test_dyn_wasm_generate COMMAND test_dyn_wasm_generate)
    set_tests_properties(test_dyn_wasm_generate PROPERTIES FIXTURES_SETUP dyn_wasm_data)

    add_executable(test_dyn_wasm_native wasm/test.cpp)
    target_link_libraries(test_dyn_wasm_native RLtools::RLtools)
    target_compile_definitions(test_dyn_wasm_native PRIVATE RL_TOOLS_TEST_DATA_PATH=${RL_TOOLS_TEST_DATA_PATH})
    add_test(NAME test_dyn_wasm_native COMMAND test_dyn_wasm_native ${RL_TOOLS_TEST_DATA_PATH}/test_dyn_wasm_checkpoint.h5)
    set_tests_properties(test_dyn_wasm_native PROPERTIES FIXTURES_REQUIRED dyn_wasm_data)
endif()
