if(NOT RL_TOOLS_BACKEND_DISABLE_BLAS)
    if(NOT RL_TOOLS_BACKEND_DISABLE_MKL)
        if(NOT MKL_ROOT)
            if(DEFINED ENV{MKL_ROOT})
                set(MKL_ROOT $ENV{MKL_ROOT})
            else()
                set(MKL_ROOT /opt/intel/oneapi/mkl/latest)
            endif()
        endif()
        find_package(MKL QUIET)
    endif()
    if(MKL_FOUND)
        target_link_libraries(rl_tools_full INTERFACE MKL::MKL)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_MKL)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_BLAS)
        set(RL_TOOLS_BACKEND_ENABLE_MKL ON)
        set(RL_TOOLS_BACKEND_ENABLE_BLAS ON)
        set(RL_TOOLS_SUMMARY_BLAS_REASON "MKL ${MKL_VERSION} (${MKL_ROOT})")
        if(NOT RL_TOOLS_BACKEND_DISABLE_DNNL)
            find_package(dnnl QUIET)
            if(dnnl_FOUND)
                target_link_libraries(rl_tools_full INTERFACE DNNL::dnnl)
                target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_DNNL)
                set(RL_TOOLS_BACKEND_ENABLE_DNNL ON)
            else()
                set(RL_TOOLS_SUMMARY_DNNL_REASON "not found")
            endif()
        endif()
    else()
        find_package(BLAS QUIET)
        if(BLAS_FOUND)
            message(VERBOSE "Found BLAS library ${BLAS_VENDOR} at ${BLAS_LIBRARIES}")
            target_link_libraries(rl_tools_full INTERFACE BLAS::BLAS)
            if(NOT APPLE)
                target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_OPENBLAS)
                target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_BLAS)
                set(RL_TOOLS_BACKEND_ENABLE_OPENBLAS ON)
                set(RL_TOOLS_BACKEND_ENABLE_BLAS ON)
                set(RL_TOOLS_SUMMARY_BLAS_REASON "OpenBLAS")
            else()
                target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_ACCELERATE)
                target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_BLAS)
                set(RL_TOOLS_BACKEND_ENABLE_ACCELERATE ON)
                set(RL_TOOLS_BACKEND_ENABLE_BLAS ON)
                set(RL_TOOLS_SUMMARY_BLAS_REASON "Accelerate")
            endif()
        else()
            set(RL_TOOLS_SUMMARY_BLAS_REASON "not found, naive fallback (e.g. apt install libopenblas-dev)")
        endif()
    endif()
endif()
