if(NOT RL_TOOLS_BACKEND_DISABLE_CUDA AND NOT WIN32) # CUDA Not supported when using MSVC right now
    cmake_minimum_required(VERSION 3.17)
    find_package(CUDAToolkit QUIET)
    if(CUDAToolkit_FOUND)
        message(STATUS "CUDAToolkit version: ${CUDAToolkit_VERSION}")
        message(STATUS "CUDAToolkit include path: ${CUDAToolkit_INCLUDE_DIRS}")
        message(STATUS "CUDAToolkit libraries: ${CUDAToolkit_LIBRARIES}")
        message(STATUS "CUDAToolkit cublas library: ${CUDAToolkit_CUBLAS_LIBRARIES}")
        set(CMAKE_CUDA_FLAGS_DEBUG "-g -G")
        if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES AND NOT DEFINED ENV{CUDAARCHS})
            set(CMAKE_CUDA_ARCHITECTURES "native")
        endif()
        if(NOT CMAKE_CUDA_COMPILER)
            set(CMAKE_CUDA_COMPILER "${CUDAToolkit_NVCC_EXECUTABLE}")
        endif()
        include(CheckLanguage)
        check_language(CUDA)
        if(NOT CMAKE_CUDA_COMPILER)
            message(STATUS "CUDA toolchain does not work (check_language(CUDA) failed), CUDA disabled.")
            set(RL_TOOLS_SUMMARY_CUDA_REASON "toolkit found but the toolchain does not work")
        else()
            target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_CUDA)
            target_link_libraries(rl_tools_full INTERFACE CUDA::cublas)
            set(RL_TOOLS_BACKEND_ENABLE_CUDA ON)
            set(RL_TOOLS_SUMMARY_CUDA_REASON "toolkit ${CUDAToolkit_VERSION}")
            if(NOT RL_TOOLS_BACKEND_DISABLE_CUDNN)
                find_library(CUDNN_LIBRARY cudnn)
                find_path(CUDNN_INCLUDE_DIR cudnn.h)
                if(CUDNN_LIBRARY AND CUDNN_INCLUDE_DIR)
                    message(STATUS "cuDNN found: ${CUDNN_LIBRARY} (include: ${CUDNN_INCLUDE_DIR})")
                    target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_CUDNN)
                    target_link_libraries(rl_tools_full INTERFACE ${CUDNN_LIBRARY})
                    target_include_directories(rl_tools_full INTERFACE ${CUDNN_INCLUDE_DIR})
                    set(RL_TOOLS_BACKEND_ENABLE_CUDNN ON)
                else()
                    message(STATUS "cuDNN not found, cuDNN-accelerated layers disabled.")
                    set(RL_TOOLS_SUMMARY_CUDNN_REASON "not found")
                endif()
            endif()
        endif()
    else()
        message(STATUS "CUDAToolkit not found, CUDA disabled.")
        set(RL_TOOLS_SUMMARY_CUDA_REASON "toolkit not found")
    endif()
endif()
