if(NOT RL_TOOLS_DISABLE_TENSORBOARD)
    find_package(Protobuf CONFIG QUIET)
    if(NOT Protobuf_FOUND)
        find_package(Protobuf QUIET)
        set(RL_TOOLS_PROTOBUF_NO_CONFIG_PACKAGE ON)
    endif()
    find_package(Git QUIET)
    if(Protobuf_FOUND AND Protobuf_PROTOC_EXECUTABLE AND GIT_FOUND)
        FetchContent_Declare(tensorboard
                GIT_REPOSITORY https://github.com/rl-tools/tensorboard_logger.git
                GIT_TAG   e1c368611062ec358af8e9e29bda8b76fd4f4910
        )
        FetchContent_MakeAvailable(tensorboard)
        target_link_libraries(rl_tools_full INTERFACE tensorboard_logger)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_TENSORBOARD)
        set(RL_TOOLS_ENABLE_TENSORBOARD ON)
    else()
        message(STATUS "Protobuf not found, TensorBoard disabled.")
    endif()
endif()
