if(NOT RL_TOOLS_DISABLE_TENSORBOARD)
    find_package(Protobuf CONFIG QUIET)
    if(NOT Protobuf_FOUND)
        find_package(Protobuf QUIET)
        set(RL_TOOLS_PROTOBUF_NO_CONFIG_PACKAGE ON)
    endif()
    if(Protobuf_FOUND AND GIT_FOUND)
        FetchContent_Declare(tensorboard
                GIT_REPOSITORY https://github.com/rl-tools/tensorboard_logger.git
                GIT_TAG   6405cc19eae874ed51ac876f4ab530205f1c0147
        )
        set(_RL_TOOLS_SAVED_BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS})
        set(BUILD_SHARED_LIBS OFF)
        rl_tools_fetchcontent_makeavailable_quiet(tensorboard)
        set(BUILD_SHARED_LIBS ${_RL_TOOLS_SAVED_BUILD_SHARED_LIBS})
        target_link_libraries(rl_tools_full INTERFACE tensorboard_logger)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_TENSORBOARD)
        set(RL_TOOLS_ENABLE_TENSORBOARD ON)
        set(RL_TOOLS_SUMMARY_TENSORBOARD_REASON "FetchContent, system protobuf ${Protobuf_VERSION}")
    elseif(NOT Protobuf_FOUND)
        set(RL_TOOLS_SUMMARY_TENSORBOARD_REASON "protobuf not found (e.g. apt install protobuf-compiler libprotobuf-dev)")
    else()
        set(RL_TOOLS_SUMMARY_TENSORBOARD_REASON "no git")
    endif()
endif()
