if(NOT RL_TOOLS_BACKEND_DISABLE_CUDA AND NOT WIN32) # CUDA Not supported when using MSVC right now
    cmake_minimum_required(VERSION 3.17)
    find_package(CUDAToolkit QUIET)
    if(CUDAToolkit_FOUND)
        message(STATUS "CUDAToolkit version: ${CUDAToolkit_VERSION}")
        message(STATUS "CUDAToolkit include path: ${CUDAToolkit_INCLUDE_DIRS}")
        message(STATUS "CUDAToolkit libraries: ${CUDAToolkit_LIBRARIES}")
        message(STATUS "CUDAToolkit cublas library: ${CUDAToolkit_CUBLAS_LIBRARIES}")
        set(CMAKE_CUDA_FLAGS_DEBUG "-g -G")
        set(CMAKE_CUDA_ARCHITECTURES "native")
        if(NOT CMAKE_CUDA_COMPILER)
            set(CMAKE_CUDA_COMPILER "${CUDAToolkit_NVCC_EXECUTABLE}")
        endif()
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_CUDA)
        target_link_libraries(rl_tools_full INTERFACE CUDA::cublas)
        set(RL_TOOLS_BACKEND_ENABLE_CUDA ON)
        find_library(CUDNN_LIBRARY cudnn HINTS ${CUDAToolkit_LIBRARY_DIR} ${CUDA_TOOLKIT_ROOT_DIR}/lib64 ${CUDA_TOOLKIT_ROOT_DIR}/lib)
        if(CUDNN_LIBRARY)
            message(STATUS "cuDNN library found: ${CUDNN_LIBRARY}")
            target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_CUDNN)
            target_link_libraries(rl_tools_full INTERFACE ${CUDNN_LIBRARY})
            set(RL_TOOLS_BACKEND_ENABLE_CUDNN ON)
        else()
            message(STATUS "cuDNN not found, cuDNN-accelerated layers disabled.")
        endif()
    else()
        message(STATUS "CUDAToolkit not found, CUDA disabled.")
    endif()
endif()
