if(NOT RL_TOOLS_DISABLE_JSON)
    find_package(nlohmann_json QUIET)
    if(nlohmann_json_FOUND)
        get_target_property(nlohmann_json_INCLUDE_DIRS nlohmann_json::nlohmann_json INCLUDE_DIRECTORIES)
        message(VERBOSE "Found existing/system nlohmann_json ${nlohmann_json_VERSION} at ${nlohmann_json_DIR}")
        target_link_libraries(rl_tools_full INTERFACE nlohmann_json::nlohmann_json)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_JSON)
        set(RL_TOOLS_ENABLE_JSON ON)
        set(RL_TOOLS_SUMMARY_JSON_REASON "system ${nlohmann_json_VERSION}")
    elseif(GIT_FOUND)
        FetchContent_Declare(nlohmann_json
                GIT_REPOSITORY https://github.com/nlohmann/json.git
                GIT_TAG        a0c1318830519eac027a31edec1a99ce1ae5670e
        )
        rl_tools_fetchcontent_makeavailable_quiet(nlohmann_json)
        target_include_directories(rl_tools_full INTERFACE ${nlohmann_json_SOURCE_DIR}/include)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_JSON)
        set(RL_TOOLS_ENABLE_JSON ON)
        set(RL_TOOLS_SUMMARY_JSON_REASON "FetchContent")
    else()
        set(RL_TOOLS_SUMMARY_JSON_REASON "not found and no git")
    endif()
endif()

if(NOT RL_TOOLS_DISABLE_HDF5)
    find_package(HDF5 QUIET)
    if(HDF5_FOUND)
        message(VERBOSE "Found existing/system HDF5 ${HDF5_VERSION} at ${HDF5_INCLUDE_DIRS}")
        target_link_libraries(rl_tools_full INTERFACE HDF5::HDF5)
        target_include_directories(rl_tools_full INTERFACE ${HDF5_INCLUDE_DIRS})
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_HDF5)
        set(RL_TOOLS_ENABLE_HDF5 ON)
        set(RL_TOOLS_SUMMARY_HDF5_REASON "system ${HDF5_VERSION}")
    else()
        set(RL_TOOLS_SUMMARY_HDF5_REASON "not found (e.g. apt install libhdf5-dev)")
    endif()
endif()


if(NOT RL_TOOLS_DISABLE_ZLIB)
    find_package(ZLIB QUIET)
    if(ZLIB_FOUND)
        message(VERBOSE "Found existing/system ZLIB ${ZLIB_VERSION} at ${ZLIB_INCLUDE_DIRS}")
        target_link_libraries(rl_tools_full INTERFACE ZLIB::ZLIB)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_ZLIB)
        set(RL_TOOLS_ENABLE_ZLIB ON)
        set(RL_TOOLS_SUMMARY_ZLIB_REASON "system ${ZLIB_VERSION}")
    elseif(GIT_FOUND)
        set(ZLIB_BUILD_EXAMPLES OFF)
        set(ZLIB_ENABLE_TESTS OFF)
        set(ZLIB_COMPAT ON)
        FetchContent_Declare(zlib
                GIT_REPOSITORY https://github.com/zlib-ng/zlib-ng.git
                GIT_TAG   8d10c309d7d468b9b2ecfd8d5f1b063d6396af17
        )
        rl_tools_fetchcontent_makeavailable_quiet(zlib)

        # zlib-ng can expose different target names depending on options/platform.
        # Resolve to an existing CMake target to avoid falling back to a raw -l flag.
        if(TARGET zlibstatic)
            set(RL_TOOLS_ZLIB_TARGET zlibstatic)
        elseif(TARGET zlib)
            set(RL_TOOLS_ZLIB_TARGET zlib)
        elseif(TARGET zlib-ng)
            set(RL_TOOLS_ZLIB_TARGET zlib-ng)
        elseif(TARGET ZLIB::ZLIB)
            set(RL_TOOLS_ZLIB_TARGET ZLIB::ZLIB)
        else()
            message(FATAL_ERROR "zlib FetchContent completed, but no expected zlib target exists (tried: zlibstatic, zlib, zlib-ng, ZLIB::ZLIB).")
        endif()
        message(VERBOSE "Using zlib target: ${RL_TOOLS_ZLIB_TARGET}")
        target_link_libraries(rl_tools_full INTERFACE ${RL_TOOLS_ZLIB_TARGET})
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_ENABLE_ZLIB)
        set(RL_TOOLS_ENABLE_ZLIB ON)
        set(RL_TOOLS_SUMMARY_ZLIB_REASON "FetchContent zlib-ng")
    else()
        set(RL_TOOLS_SUMMARY_ZLIB_REASON "not found and no git")
    endif()
endif()
