if(NOT MKL_ROOT)
    set(MKL_ROOT /opt/intel/oneapi/mkl/latest)
    message(STATUS "MKL_ROOT is not set. Using default: ${MKL_ROOT}")
endif()
find_package(MKL QUIET)
if(MKL_FOUND)
    message(STATUS "Found MKL ${MKL_VERSION}")
    target_link_libraries(rl_tools_full INTERFACE MKL::MKL)
    target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_MKL)
    set(RL_TOOLS_BACKEND_ENABLE_MKL ON)
else()
    find_package(BLAS QUIET)
    if(BLAS_FOUND)
        message(STATUS "Found BLAS library ${BLAS_VERSION}")
        target_link_libraries(rl_tools_full INTERFACE BLAS::BLAS)
        if(RL_TOOLS_BACKEND_ENABLE_OPENBLAS)
            target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_OPENBLAS)
            set(RL_TOOLS_BACKEND_ENABLE_OPENBLAS ON)
        else()
            target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_ACCELERATE)
            set(RL_TOOLS_BACKEND_ENABLE_ACCELERATE ON)
        endif()
    else()
        message(WARNING "BLAS no BLAS library found, defaulting to naive backend. Performance will be suboptimal.")
    endif()
endif()

