if(NOT RL_TOOLS_RL_ENVIRONMENTS_DISABLE_MUJOCO)
    set(MUJOCO_BUILD_EXAMPLES OFF)
    set(MUJOCO_BUILD_SIMULATE OFF)
    set(MUJOCO_BUILD_TESTS OFF)
    set(MUJOCO_TEST_PYTHON_UTIL OFF)
    find_package(mujoco QUIET)
    if(mujoco_FOUND)
        message(STATUS "Found existing/system mujoco ${mujoco_VERSION} at ${mujoco_DIR}")
        set(RL_TOOLS_SUMMARY_MUJOCO_REASON "system ${mujoco_VERSION}")
    elseif(GIT_FOUND)
        FetchContent_Declare(mujoco
                GIT_REPOSITORY https://github.com/google-deepmind/mujoco.git
                GIT_TAG   2.3.5
        )
        rl_tools_fetchcontent_makeavailable_quiet(mujoco)
        # MuJoCo 2.3.5 hardcodes -Werror; its warning set predates current compilers (e.g. GCC 15)
        function(rl_tools_mujoco_strip_werror STRIP_DIRECTORY)
            get_property(RL_TOOLS_STRIP_TARGETS DIRECTORY ${STRIP_DIRECTORY} PROPERTY BUILDSYSTEM_TARGETS)
            foreach(RL_TOOLS_STRIP_TARGET IN LISTS RL_TOOLS_STRIP_TARGETS)
                get_target_property(RL_TOOLS_STRIP_OPTIONS ${RL_TOOLS_STRIP_TARGET} COMPILE_OPTIONS)
                if(RL_TOOLS_STRIP_OPTIONS AND "-Werror" IN_LIST RL_TOOLS_STRIP_OPTIONS)
                    list(REMOVE_ITEM RL_TOOLS_STRIP_OPTIONS "-Werror")
                    set_target_properties(${RL_TOOLS_STRIP_TARGET} PROPERTIES COMPILE_OPTIONS "${RL_TOOLS_STRIP_OPTIONS}")
                endif()
            endforeach()
            get_property(RL_TOOLS_STRIP_SUBDIRECTORIES DIRECTORY ${STRIP_DIRECTORY} PROPERTY SUBDIRECTORIES)
            foreach(RL_TOOLS_STRIP_SUBDIRECTORY IN LISTS RL_TOOLS_STRIP_SUBDIRECTORIES)
                rl_tools_mujoco_strip_werror(${RL_TOOLS_STRIP_SUBDIRECTORY})
            endforeach()
        endfunction()
        rl_tools_mujoco_strip_werror(${mujoco_SOURCE_DIR})
        set(RL_TOOLS_SUMMARY_MUJOCO_REASON "FetchContent 2.3.5")
    else()
        message(STATUS "MuJoCo disabled (not found and no git)")
        set(RL_TOOLS_SUMMARY_MUJOCO_REASON "not found and no git")
    endif()
    if(mujoco_FOUND OR TARGET mujoco::mujoco OR TARGET mujoco)
        set(RL_TOOLS_RL_ENVIRONMENTS_ENABLE_MUJOCO ON)
        target_link_libraries(rl_tools_full INTERFACE mujoco::mujoco)
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_RL_ENVIRONMENTS_ENABLE_MUJOCO)

        find_package(glfw3 QUIET)
        if(glfw3_FOUND)
            message(STATUS "Found existing/system glfw3 ${glfw3_VERSION} at ${glfw3_DIR}")
        elseif(GIT_FOUND)
            set(RL_TOOLS_MUJOCO_UI_BUILDABLE ON)
            if(UNIX AND NOT APPLE)
                # building glfw from source hard-requires the X11 dev headers on Linux
                find_package(X11 QUIET)
                if(NOT X11_FOUND)
                    set(RL_TOOLS_MUJOCO_UI_BUILDABLE OFF)
                    message(STATUS "MuJoCo UI disabled (X11 dev headers not found, required to build glfw)")
                endif()
            endif()
            if(RL_TOOLS_MUJOCO_UI_BUILDABLE)
                FetchContent_Declare(glfw3
                        GIT_REPOSITORY https://github.com/glfw/glfw.git
                        GIT_TAG   3fa2360720eeba1964df3c0ecf4b5df8648a8e52
                )
                rl_tools_fetchcontent_makeavailable_quiet(glfw3)
            endif()
        endif()
        if(glfw3_FOUND OR TARGET glfw)
            target_link_libraries(rl_tools_full INTERFACE glfw)
            set(RL_TOOLS_RL_ENVIRONMENTS_MUJOCO_ENABLE_UI ON)
            target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_RL_ENVIRONMENTS_MUJOCO_ENABLE_UI)
        elseif(NOT GIT_FOUND)
            message(STATUS "MuJoCo UI disabled (glfw not found and no git)")
        endif()
    endif()
endif()
