# Raytracing backend dispatch. AUTO probes availability in preference order
# OPTIX > METAL > VULKAN > WEBGPU > GENERIC; an explicitly selected backend is hard-required.
# All backends need assimp, so without it raytracing auto-disables entirely.
if(NOT RL_TOOLS_RENDERING_DISABLE_RAYTRACING)
    set(RL_TOOLS_RENDERING_RAYTRACING_BACKENDS OPTIX METAL VULKAN WEBGPU GENERIC)
    if(NOT RL_TOOLS_RENDERING_RAYTRACING_BACKEND STREQUAL "AUTO" AND NOT RL_TOOLS_RENDERING_RAYTRACING_BACKEND IN_LIST RL_TOOLS_RENDERING_RAYTRACING_BACKENDS)
        message(FATAL_ERROR "Invalid RL_TOOLS_RENDERING_RAYTRACING_BACKEND: ${RL_TOOLS_RENDERING_RAYTRACING_BACKEND} (AUTO|OPTIX|METAL|VULKAN|WEBGPU|GENERIC)")
    endif()
    find_package(assimp QUIET)
    if(NOT assimp_FOUND)
        if(RL_TOOLS_RENDERING_RAYTRACING_BACKEND STREQUAL "AUTO")
            message(STATUS "RLtools raytracing disabled (assimp not found - e.g. apt install libassimp-dev)")
            set(RL_TOOLS_SUMMARY_RAYTRACING_REASON "assimp not found")
        else()
            message(FATAL_ERROR "RLtools raytracing backend ${RL_TOOLS_RENDERING_RAYTRACING_BACKEND} requested but assimp was not found (e.g. apt install libassimp-dev)")
        endif()
    else()
        set(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED ${RL_TOOLS_RENDERING_RAYTRACING_BACKEND})
        if(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED STREQUAL "AUTO")
            set(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED "GENERIC")
            set(RL_TOOLS_RAYTRACING_OPTIX_UNAVAILABLE_REASON "")
            if(RL_TOOLS_RENDERING_RAYTRACING_DISABLE_OPTIX)
                set(RL_TOOLS_RAYTRACING_OPTIX_UNAVAILABLE_REASON "disabled by RL_TOOLS_RENDERING_RAYTRACING_DISABLE_OPTIX")
            elseif(WIN32)
                set(RL_TOOLS_RAYTRACING_OPTIX_UNAVAILABLE_REASON "not supported on Windows")
            elseif(NOT RL_TOOLS_BACKEND_ENABLE_CUDA)
                set(RL_TOOLS_RAYTRACING_OPTIX_UNAVAILABLE_REASON "CUDA unavailable")
            elseif(NOT ((GIT_FOUND AND NOT RL_TOOLS_OFFLINE_BUILD) OR EXISTS "${FETCHCONTENT_BASE_DIR}/owl-src"))
                set(RL_TOOLS_RAYTRACING_OPTIX_UNAVAILABLE_REASON "cannot fetch OWL (offline/no git)")
            endif()

            set(RL_TOOLS_RAYTRACING_METAL_UNAVAILABLE_REASON "")
            if(RL_TOOLS_RENDERING_RAYTRACING_DISABLE_METAL)
                set(RL_TOOLS_RAYTRACING_METAL_UNAVAILABLE_REASON "disabled by RL_TOOLS_RENDERING_RAYTRACING_DISABLE_METAL")
            elseif(NOT APPLE)
                set(RL_TOOLS_RAYTRACING_METAL_UNAVAILABLE_REASON "not on macOS")
            else()
                find_library(RL_TOOLS_METAL_FRAMEWORK Metal)
                find_library(RL_TOOLS_FOUNDATION_FRAMEWORK Foundation)
                find_library(RL_TOOLS_QUARTZCORE_FRAMEWORK QuartzCore)
                if(NOT (RL_TOOLS_METAL_FRAMEWORK AND RL_TOOLS_FOUNDATION_FRAMEWORK AND RL_TOOLS_QUARTZCORE_FRAMEWORK))
                    set(RL_TOOLS_RAYTRACING_METAL_UNAVAILABLE_REASON "Metal/Foundation/QuartzCore frameworks not found")
                endif()
            endif()

            set(RL_TOOLS_RAYTRACING_VULKAN_UNAVAILABLE_REASON "")
            if(RL_TOOLS_RENDERING_RAYTRACING_DISABLE_VULKAN)
                set(RL_TOOLS_RAYTRACING_VULKAN_UNAVAILABLE_REASON "disabled by RL_TOOLS_RENDERING_RAYTRACING_DISABLE_VULKAN")
            else()
                find_package(Vulkan QUIET COMPONENTS glslangValidator)
                if(NOT Vulkan_FOUND OR NOT Vulkan_glslangValidator_FOUND)
                    set(RL_TOOLS_RAYTRACING_VULKAN_UNAVAILABLE_REASON "Vulkan headers or glslangValidator not found (e.g. apt install libvulkan-dev glslang-tools)")
                endif()
            endif()

            set(RL_TOOLS_RAYTRACING_WEBGPU_UNAVAILABLE_REASON "")
            if(RL_TOOLS_RENDERING_RAYTRACING_DISABLE_WEBGPU)
                set(RL_TOOLS_RAYTRACING_WEBGPU_UNAVAILABLE_REASON "disabled by RL_TOOLS_RENDERING_RAYTRACING_DISABLE_WEBGPU")
            elseif(NOT (CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64"))
                set(RL_TOOLS_RAYTRACING_WEBGPU_UNAVAILABLE_REASON "only wired up on linux-x86_64")
            elseif(RL_TOOLS_OFFLINE_BUILD AND NOT EXISTS "${FETCHCONTENT_BASE_DIR}/wgpu_native-src")
                set(RL_TOOLS_RAYTRACING_WEBGPU_UNAVAILABLE_REASON "cannot fetch wgpu-native (offline)")
            endif()

            foreach(RL_TOOLS_RAYTRACING_CANDIDATE OPTIX METAL VULKAN WEBGPU)
                if(RL_TOOLS_RAYTRACING_${RL_TOOLS_RAYTRACING_CANDIDATE}_UNAVAILABLE_REASON STREQUAL "")
                    set(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED ${RL_TOOLS_RAYTRACING_CANDIDATE})
                    break()
                else()
                    message(STATUS "RLtools raytracing backend candidate ${RL_TOOLS_RAYTRACING_CANDIDATE} skipped: ${RL_TOOLS_RAYTRACING_${RL_TOOLS_RAYTRACING_CANDIDATE}_UNAVAILABLE_REASON}")
                endif()
            endforeach()
            set(RL_TOOLS_SUMMARY_RAYTRACING_REASON "backend ${RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED}, auto-selected")
        else()
            if(RL_TOOLS_RENDERING_RAYTRACING_DISABLE_${RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED})
                message(FATAL_ERROR "RL_TOOLS_RENDERING_RAYTRACING_BACKEND=${RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED} conflicts with RL_TOOLS_RENDERING_RAYTRACING_DISABLE_${RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED}=ON")
            endif()
            set(RL_TOOLS_SUMMARY_RAYTRACING_REASON "backend ${RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED}, explicitly selected")
        endif()
        message(STATUS "RLtools raytracing backend: ${RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED} (AUTO preference: OPTIX > METAL > VULKAN > WEBGPU > GENERIC)")
        if(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED STREQUAL "METAL")
            include(cmake/optional/metal.cmake)
        elseif(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED STREQUAL "OPTIX")
            include(cmake/optional/optix.cmake)
        elseif(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED STREQUAL "VULKAN")
            include(cmake/optional/vulkan.cmake)
        elseif(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED STREQUAL "WEBGPU")
            include(cmake/optional/webgpu.cmake)
        elseif(RL_TOOLS_RENDERING_RAYTRACING_BACKEND_RESOLVED STREQUAL "GENERIC")
            include(cmake/optional/raytracing_generic.cmake)
        endif()
        set(RL_TOOLS_RENDERING_ENABLE_RAYTRACING ON)
    endif()
else()
    set(RL_TOOLS_SUMMARY_RAYTRACING_REASON "disabled by RL_TOOLS_RENDERING_DISABLE_RAYTRACING")
endif()
