add_executable(rendering_raytracing_yaw_prediction_swift_app_h5_to_tar h5_to_tar.cpp)
set_target_properties(rendering_raytracing_yaw_prediction_swift_app_h5_to_tar PROPERTIES CXX_STANDARD 17)
target_include_directories(rendering_raytracing_yaw_prediction_swift_app_h5_to_tar PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_link_libraries(rendering_raytracing_yaw_prediction_swift_app_h5_to_tar PRIVATE rl_tools_full HighFive)
